### ISSUE TITLE
Grav needs permission changes

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#100]
See https://learn.getgrav.org/troubleshooting/permissions

@JoyceGross can you take a look when you have a chance? The file 

[`/usr/local/web/amphibiaweb_disease/grav/set-permissions.sh`](https://github.com/AmphibiaWeb/amphibian-disease-tracker/blob/master/grav/set-permissions.sh)

sets up permissions as suggested in the docs, but there may be more robust solutions involving custom groups. Perhaps a group with users with filesystem write + apache, something like `www-data-writeable`, and directories with that owner can have members change permissions? (Then the owner wouldn't need changing, just the group, and if apache does permission juggling it should "just work")

**Comment by JoyceGross** [comment]
From the troubleshooting page. #1 is not possible on our server. #2 may not be possible either. I'd have to ask Igor. (I'm a little reluctant to ask....) #3 -- The script would have to be run as root every time a file is edited? If so, that's not a good solution. If it's a one-time thing, I can do it.

Can you explain your other idea more? I'm afraid I don't understand.

apache does not have many permissions on the server, on purpose.

**Comment by JoyceGross** [comment]
This numbers were not meant to be links to anything... sorry. They are referring to the numbers on this page
https://learn.getgrav.org/troubleshooting/permissions

**Comment by jdeck88** [comment]
Nothing says "havoc" better than a 3rd party PHP script w/ file writing
permissions.
I agree w/ Joyce on #1 and #2 --- #2 is a bit better than being world
writeable, but agreed we probably shouldn't go there.
For #3, is joeblow the account the webserver process runs under?   This
sounds like it would have be run as a cronjob under root. (or run
manually)--- this doesn't sound like a great idea either.

John

On Wed, May 11, 2016 at 12:21 AM, JoyceGross <notifications@github.com>
wrote:

> This numbers were not meant to be links to anything... sorry. They are
> referring to the numbers on this page
> https://learn.getgrav.org/troubleshooting/permissions
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/100#issuecomment-218381718>
>



-- 
John Deck
(541) 914-4739

**Comment by mkoo** [comment]
For something that was  suppose to be 'easy to install' it's kinda not.
Philip and I should discuss whether we really want to 'try' this. I'm in
favor of ditching it for now since it carries more pain than promise at the
moment!

**Comment by tigerhawkvok** [comment]
@JoyceGross the permissions are a one-time script ( @jdeck88 the file writing is supposed to be limited in scope). Basically those directories need the same permissions a Wordpress install would (which @mkoo is worth noting! If these permissions aren't manageable, then WP wouldn't work on MVZ servers, either, as it writes files all the time for uploads and such)

**Comment by jdeck88** [comment]
My 2 cents....

Good point re: WP, however, we've spent alot of time making safeguards,
updating plugins, and monitoring the system closely, w/ daily monitoring
scripts to let us know what is happening -- basically its been a headache,
but the payoff is high since museums really need/want WP.   So, yes....
there is risk and work for WP but we've decided its worth it.

OTOH, if the permissions  settings are just a one-time script (it sounded
like they would need to be modified continually), then maybe not such a big
deal, but still something that will take work to make sure it is up to
date, and configured properly and we manage the risk appropriately.  So,
the short story, from my point of view is that if it is lots better than
readthedocs or other systems that don't require the systems admin headaches
on our end than we can think about proceeding, just want to make sure it is
worth the effort and whatever risk comes with it.

John

On Wed, May 11, 2016 at 9:57 AM, Philip Kahn <notifications@github.com>
wrote:

> @JoyceGross <https://github.com/JoyceGross> the permissions are a
> one-time script ( @jdeck88 <https://github.com/jdeck88> the file writing
> is supposed to be limited in scope). Basically those directories need the
> same permissions a Wordpress install would (which @mkoo
> <https://github.com/mkoo> is worth noting! If these permissions aren't
> manageable, then WP wouldn't work on MVZ servers, either, as it writes
> files all the time for uploads and such)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/100#issuecomment-218522046>
>



-- 
John Deck
(541) 914-4739

**Comment by JoyceGross** [comment]
If option 3 only needs to be run once, I can give it a try. What users exactly should be the places of joeblow and staff?
chown joeblow:staff

**Comment by tigerhawkvok** [comment]
Owner should probably be apache's `www-data`, and the group probably general user group `mvz` so that we still have write permissions even though Apache owns it .... sound sensible?

**Comment by JoyceGross** [comment]
apache is only in group apache... there is no www-data group. ok to use that instead?

**Comment by tigerhawkvok** [comment]
Should be just fine!

On Wed, May 11, 2016, 13:43 JoyceGross <notifications@github.com> wrote:

> apache is only in group apache... there is no www-data group. ok to use
> that instead?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/100#issuecomment-218584277>
>
-- 


-via Nexus 6P-

---------------------------
Philip Kahn
1314 Hopkins St
Berkeley CA
94702
510.859.3142
---------------------------

**Comment by JoyceGross** [comment]
Philip --  you were right about www-data. All the other servers I work on use "apache" for the user name that runs the web server. Not aldo. (Also I had another typo in my last post ... ugh. Doesn't matter now though.)

Anyway, I ran this:

chown www-data:mvz .
chown -R www-data:mvz *
find . -type f | xargs chmod 664
find ./bin -type f | xargs chmod 775
find . -type d | xargs chmod 775
find . -type d | xargs chmod +s
umask 0002

Let me know what happens now with grav.

**Comment by tigerhawkvok** [comment]
Too buggy, let's not bother. Read the docs!
