### ISSUE TITLE
Default field order on FIMS xlsx

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#101]
User comment:

>[...] just so counter-intuitive to have latitude before longitude column, and species before genus column!!

@jdeck88 , is this configurable?

**Comment by jdeck88** [comment]
I added you use a collaborator to biocode-fims repo:

https://raw.githubusercontent.com/biocodellc/biocode-fims/master/Documents/AmphibianDisease/amphibiandisease.xml

change order of attributes in mapping->entity section and you're good to go.
You can also login to FIMS and change the location of the configuration file for the project if you wish to store it somewhere else.
