### ISSUE TITLE
when toggle map markers, show unique species list for given disease status

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#102]
- [x] On the Project details page, you can toggle map markers on map-- a feature request would be to show a unique species list for all Positive, negative, inconclusive results when toggling map markers

- [ ] Related, can download of unique species list contain summary of results?

**Comment by tigerhawkvok** [comment]
The first half of this is already implemented

![screenshot 264](https://cloud.githubusercontent.com/assets/165937/15130678/36ce5fd0-15ff-11e6-8158-060b745ad281.png)


![screenshot 263](https://cloud.githubusercontent.com/assets/165937/15130674/31977808-15ff-11e6-89bc-46b34f6e9d8b.png)

![screenshot 265](https://cloud.githubusercontent.com/assets/165937/15130681/3c66a8d0-15ff-11e6-8267-32d5ab7f1ea0.png)

**Comment by tigerhawkvok** [comment]
What should the

> Related, can download of unique species list contain summary of results?

contain?

I added a column for "has positive", "has negative", and "has inconclusive". 

Bounds or some such?


[Current sample: species-list-b497f2a5ab33bfa2943c797856f01e57-2016-07-04T22-15-09.209Z.xlsx](https://github.com/AmphibiaWeb/amphibian-disease-tracker/files/346872/species-list-b497f2a5ab33bfa2943c797856f01e57-2016-07-04T22-15-09.209Z.xlsx)

**Comment by mkoo** [comment]
I like the summary of data-- please also include: total count, count
positive, count negative, count inconclusive. Those tallies will be
valuable.
