### ISSUE TITLE
Record-level global search fun

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#104]
See #33 

Kind of an advanced search and aggregated record search 

Search on

- Taxa
- Detection
- Morbidity? 
- Bounds
- Manual column specification -- see #74 

Lookup appropriate projects locally, then do a joined query on carto against those tables

Needs to then be downloaded as a result blob. Blocking #106

**Comment by mkoo** [comment]
This is the main access point of the project. Eventually the home page
should land us to the main search portal.

**Comment by tigerhawkvok** [comment]
Search functions completed generically, visualization pending
