### ISSUE TITLE
uploading profile image unresponsive

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#105]
what formats are allowed? tried png and jpg so far...

**Comment by tigerhawkvok** [comment]
Not completed yet, those should both work when it is .... 

that and auto-linking are the last two profile checkboxes to finish profiles in entirety

**Comment by tigerhawkvok** [comment]
Fixed as of 5a9f00637045dc4dd4b42eda5b44b7a9acb9228b

![image](https://cloud.githubusercontent.com/assets/165937/15767379/4f8dcb9a-28fc-11e6-83c5-f6dceee45fa8.png)

![image](https://cloud.githubusercontent.com/assets/165937/15767392/5cf4e764-28fc-11e6-973b-696f99b8dcc6.png)

![image](https://cloud.githubusercontent.com/assets/165937/15767395/64ec07e0-28fc-11e6-8d3e-70a2b0ee66aa.png)
