### ISSUE TITLE
Visualize Global Samples

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#106]
Heat map data would be great

Color code by recency? Use a Carto embed for this, rather than a `<google-map>` pinsplosion.

See #104 (blocked on)

**Comment by mkoo** [comment]
Use Cartodb! They have great built in visualization tools and CartoCSS to
help customize. Let me know if you want me to weigh in but those map
examples are fully viewable by you to see how they were set up.

**Comment by tigerhawkvok** [comment]
For whatever reason, this isn't visualizing as expected.

Reference for problem: https://gis.stackexchange.com/questions/196115/using-createlayer-in-cartodb-isnt-working

**Comment by tigerhawkvok** [comment]
Need to convert back-end API to "Named Maps" -- see

- http://gis.stackexchange.com/a/197180/62853
- https://docs.cartodb.com/cartodb-platform/maps-api/named-maps/

**Comment by tigerhawkvok** [comment]
Migrated to "Named Maps", which looks like it acts correctly


![screenshot 2016-06-15 13 29 41](https://cloud.githubusercontent.com/assets/165937/16096602/9f97afdc-32fe-11e6-925b-7c4047a41e2e.png)

but the points aren't loaded as per this JSFiddle https://jsfiddle.net/tigerhawkvok/q1nq89s1/ ...

**Comment by tigerhawkvok** [comment]
Displaying now!

![screenshot 2016-06-17 14 02 13](https://cloud.githubusercontent.com/assets/165937/16164673/5be93192-3494-11e6-8de0-dbfd70c0df6f.png)


To-Do:

- [ ] Color code by project recency
- [ ] Initialize with all points from all tables visible
