### ISSUE TITLE
better error message on password requirements

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#11]
troubleshoot the registration process since it was not clear to users that they had a password that does not meet requirements

**Comment by tigerhawkvok** [comment]
Any suggestions for improvement?

![image](https://cloud.githubusercontent.com/assets/165937/11863370/44e037d4-a448-11e5-8845-e5b979892439.png)

**Comment by tigerhawkvok** [comment]
Closing with no further complaints on the issue
