### ISSUE TITLE
Project pages to show bibliographic citation if based on publication + copy button

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#113]
Generally speaking DOI's are not useful for people! Since we already have a spot for DOI, can we have a parsed out citation?
See doi citation generator as example:
https://mickschroeder.com/citation/?q=10.1007%2Fs10393-015-1071-y

Also add in text box for those without doi's

**Comment by tigerhawkvok** [comment]
Should this be a target before SSAR? I noticed this has no milestone attached.

**Comment by mkoo** [comment]
not a priority for demo

**Comment by tigerhawkvok** [comment]
Complete

![image](https://cloud.githubusercontent.com/assets/165937/16570548/24041588-41fc-11e6-892e-f16657740e73.png)


![image](https://cloud.githubusercontent.com/assets/165937/16570550/37f8bb7a-41fc-11e6-83d1-547e3a5e5a25.png)


Should there also be a copy for the citation, or is the `readonly` textfield sufficient?

The open button opens up the PDF url, if applicable

**Comment by mkoo** [comment]
nice! Copy button next to Open would be fantastic. I will definitely show
this off.

**Comment by tigerhawkvok** [comment]
I think I got the formatting right for print, online-only, and in-press, but let me know if I missed an edge case.

Re-opening for copy
