### ISSUE TITLE
New ARKs aren't resolving with N2T.net

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#121]
New ARKs aren't resolving. 

For example, https://n2t.net/ark:/21547/ARj2 returns 404 not found, as well as https://n2t.net/ark:/21547/ARm2

Resolver still works with `http://biscicol.org/id/` prefix, but no longer `https://n2t.net` (eg, http://biscicol.org/id/ark:/21547/ARm2 ).

Additionally, `biscicol.org` has no `https` option (so, http://biscicol.org/id/ark:/21547/ARm2 returns a `ERR_CONNECTION_CLOSED`)

**Comment by jdeck88** [comment]
This is fixed. EZIDs were not getting registered due to an introduced bug but now all the ones you requested have not been registered.

Https is a different issue, closing this one for now. if you need it you can submit a new issue w/ enhancement request.
