### ISSUE TITLE
Remove recency color coding

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#124]
Either use uniform color or heatmap.

Heatmap needs some cartocss love, or a different base map layer, or both.

**Comment by mkoo** [comment]
And what we end up doing, we need a legend!

**Comment by tigerhawkvok** [comment]
Broke heatmaps (and legends) into #132 for the F&W milestone. Solid color added at f447e662596004deebae1014e0fcefe9846c4908
