### ISSUE TITLE
Allow Edit box for Project Abstract to be expandable

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#129]
so much unused real estate!      

![screen shot 2016-06-30 at 9 01 05 pm](https://cloud.githubusercontent.com/assets/2523089/16511544/187423a0-3f06-11e6-8d02-d62e6bb33453.png)

**Comment by tigerhawkvok** [comment]
Ack! Actually should be 100% of that container.
