### ISSUE TITLE
Adding new data to a project with no data bugs out

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#138]
Eep,

**Comment by tigerhawkvok** [comment]
For @mkoo 's [CA Island project](https://amphibiandisease.org/project.php?id=b497f2a5ab33bfa2943c797856f01e57), it's now successfully erroring to where it should with the last provided dataset:

![image](https://cloud.githubusercontent.com/assets/165937/16542364/7c25821e-4059-11e6-8f27-35850ddc0cb2.png)

**Comment by mkoo** [comment]
Not sure if ready to close.

I fixed the data errors and then held breath until this:
Not sure what the issue is

[image: Inline image 1]

**Comment by tigerhawkvok** [comment]
Hm, that image didn't show correctly. Try again?

**Comment by tigerhawkvok** [comment]
and/or send me the revised data template (or post a restricted permission drive link?)

**Comment by mkoo** [comment]
red bar at top of screen saying "Cannot Load data at this time. Please try
again later."

Happens after the validation steps which seemed successful.
so close!

**Comment by tigerhawkvok** [comment]
Update: I debugged the initial timeout error, but right now I'm trying to track down an unexpected syntax error. I found one of them, but there's another that I'm having a hard time tracing. I'm installing PostgreSQL locally to test out.

**Comment by mkoo** [comment]
Got it.. Thanks!

**Comment by tigerhawkvok** [comment]
UPDATE: Fixed an escaping quote issue, which fixed part of it, but this dataset has such wildly varying lengths of additional information I've been getting `414 Request Too Large` errors, so now rewriting the way statements are prepared
