### ISSUE TITLE
Project Links from Search results are Undefined

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#148]
While the hover works to see the project associated with the data, the URL is id=undefined
Here's URL that is from the link:

https://amphibiandisease.org/project.php?id=undefined

**Comment by tigerhawkvok** [comment]
Do you have a specific search that failed?

Seaches for "gabon", "vre", and "batra" all had corresponding links that loaded fine for me.

**Comment by mkoo** [comment]
Wasnt the search-- it was the links to _Project_ from the search results
when searching datasets (eg. the arrow link) that had an empty project_id
value.

this is result when clicking on arrow link

[image: Inline image 1]
