### ISSUE TITLE
draw a bounding box map interface

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#15]
specifically for a Project

**Comment by mkoo** [comment]
Addresses feature request #6, related to #17

**Comment by tigerhawkvok** [comment]
Note: This relates to a GUI method of drawing a bounding box, rather than the currently input-able coordinate list or region search.

**Comment by tigerhawkvok** [comment]
A "nice" UI for this is blocked on https://github.com/GoogleWebComponents/google-map/issues/255

See https://jsfiddle.net/tigerhawkvok/ofu7dfnm/8/

**Comment by tigerhawkvok** [comment]
Clean UI workaround found; droppable, visible pins as of 443facd4db6ead538f970f430deb5e107c9fa0e2

Before clicking "Build Map":

![screenshot 2016-03-03 21 30 29](https://cloud.githubusercontent.com/assets/165937/13518854/20ff2ec0-e187-11e5-9279-a7075f55f6e1.png)


After: 

![image](https://cloud.githubusercontent.com/assets/165937/13518861/3789671e-e187-11e5-82f2-98f362db76fb.png)
