### ISSUE TITLE
Search Results need to be highlighted better

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#155]
Right now search results are mapped and a line in gray appears with the summary of the results-- see screenshot. Line in red box needs to be in a darker font color like dark blue or green or highlighted in a box? Feedback says people are missing it entirely.
![screenshot-amphibiandisease org 2016-07-22 15-57-20](https://cloud.githubusercontent.com/assets/2523089/17073422/999a5c58-5025-11e6-96b7-e23624d55e06.png)

**Comment by mkoo** [comment]
Suggest Search Result Table (from VV)

SEARCH RESULTS:
We found 656 samples including from 6 species
Table
tests for Batrachochytrium dendrobatidis 
species                            // total samples // Bd positive  // Bd negative   // Bd prevalence

Batrachoseps pacificus    //  122             //  23              //   99               // 7.8 %
Batrachoseps gregarious // 100              // 10               // 90                  // 10 %

tests for Batrachochytrium salamandrivorans
(no results)

**Comment by tigerhawkvok** [comment]
Blurb already done:

![image](https://cloud.githubusercontent.com/assets/165937/17545171/867727ea-5e90-11e6-8d9c-4ff10120b2de.png)

Table should be in popup, since the data size could be large. See #167
