### ISSUE TITLE
Abstract Preview not previewing

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#161]
Not sure why but when editing the abstract box, no Preview!
Editing box:
![screenshot-amphibiandisease org 2016-08-02 13-11-47](https://cloud.githubusercontent.com/assets/2523089/17343513/f07763aa-58b2-11e6-9473-725309da330b.png)

Preview box:
![screenshot-amphibiandisease org 2016-08-02 13-12-16](https://cloud.githubusercontent.com/assets/2523089/17343521/fe5fc05c-58b2-11e6-927f-9e0ecd40869b.png)

**Comment by tigerhawkvok** [comment]
From the same project, I can't replicate:

![screenshot 2016-08-10 00 25 39](https://cloud.githubusercontent.com/assets/165937/17545273/128b0c1a-5e91-11e6-860a-a6a7102816d5.png)


![image](https://cloud.githubusercontent.com/assets/165937/17545257/00fb64cc-5e91-11e6-8afa-aebfbe395f8c.png)

**Comment by mkoo** [comment]
ok, it appears to be related to Mac/FF Adblocker extension weirdness. Only
happens in that circumstance and "fixed" when disabled, so should be closed
