### ISSUE TITLE
Investigate overlaying a polygon from coordinates on a map via cartodb

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#17]
ARGH WHERE IS THE LINK

**Comment by mkoo** [comment]
Can you use google maps api?
See Arctos' draw a bounding box for coordinates selection here  (click on
Select on Google Map):
http://arctos.database.museum/SpecimenSearch.cfm

we can ask Dusty the specifics.

**Comment by tigerhawkvok** [comment]
Got a bounding box set up for an arbitrarily sorted list of point (defaults to four, box)

![screenshot 148](https://cloud.githubusercontent.com/assets/165937/11806728/f3935de0-a2c9-11e5-9bac-f5237a74fc8f.png)

![screenshot 149](https://cloud.githubusercontent.com/assets/165937/11806735/f76b2290-a2c9-11e5-8752-b58615e0dc03.png)


(Fun fact: Google Maps draws the box in coordinate order, so you have to write an algo to SORT a randomly-given set of points ...)
