### ISSUE TITLE
create toggle for the pop-up window "Welcome" on the home page

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#177]
Right now, first time log-on (according to cookies) is the only time users see the Welcome box with helpful links. Users should be able to see that box at will.

**Comment by tigerhawkvok** [comment]
"Show welcome" is now available in a new home page overflow menu.

Fixed at 59d3d1288e62a9489181133ac81cf0cbddbc5aad
