### ISSUE TITLE
Check encoding/de-encoding algo to database

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#182]
Some special characters and most accented characters break.

>basic symbols that break:  - % degree symbols, etc

Don't know where in the pipeline this occurs.

**Comment by tigerhawkvok** [comment]
Dyslexic moment: Fixed at b55bbc596c72bb022db98994b5211934775286f7, which has a bad commit message

**Comment by mkoo** [comment]
check the project data

**Comment by tigerhawkvok** [comment]
@mkoo , something happened to the Koñespata upload/save -- the carto database associated with it never saved. To debug this, I need to do some uploads, so for now this is blocked on #183
