### ISSUE TITLE
Need to figure out canonical way to handle bad localities

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#192]
Such as multi-continent ones!

**Comment by mkoo** [comment]
how can a locality be multicontinental?!

**Comment by tigerhawkvok** [comment]
@mkoo exactly my initial thought, but that was the issue with Alessandro's dataset (MCP was intercontinental)

**Comment by mkoo** [comment]
to be clear, it;s not the records that are bad but the generated MCP.
Related to #195 (right?)

**Comment by tigerhawkvok** [comment]
This issue should be rendered obsolete by #198 , #197
