### ISSUE TITLE
Enable KML uploads

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#197]

**Comment by tigerhawkvok** [comment]
Fixed at bad67974708e6ff60ca4a5bbfd3e424bfe3ff6ac

**Comment by mkoo** [comment]
Reopening this issue since from my view it's not ready....

Uploading KML from project-editing causing endless validation ...

Uploading KML from project-creation does not cause error but it is not visible in Project Browser (even Private projects should have their project bounding boxes/KMLs visible)

**Comment by tigerhawkvok** [comment]
@mkoo do you have a project that it was uploaded from creation but isn't visible in the browser? theoretically ti should "look" identical to the MCP generated from the data ...

Fixed the endless validation @ de74dd79fbee1dacdcba5f1207253e54ead23b12 (didn't close that window, whoops)

**Comment by mkoo** [comment]
@tigerhawkvok I've been uploading to this cleverly named project:
https://amphibiandisease.org/project.php?id=8fa4de1eb2ebed92ea059d242d577893

this is the [KML](https://www.dropbox.com/s/xkz4qgdy6kkeoi5/Bsal_Mtns.kml?dl=0)

I can see it in edit mode but not in project viewer.

Help?!

**Comment by tigerhawkvok** [comment]
@mkoo fixed: 

- multipart kml renders on main map
- kml renders on map when there's no established data locality (what was tripping up yours in particular)
- multipart KML renders for private projects (needed independent recalculations per bounds set)

![image](https://cloud.githubusercontent.com/assets/165937/20084947/84b66076-a51a-11e6-88b5-275c9f3d2ba8.png)

![image](https://cloud.githubusercontent.com/assets/165937/20084955/8a833e52-a51a-11e6-8883-3bee71c078d2.png)


![image](https://cloud.githubusercontent.com/assets/165937/20084959/9269ed6e-a51a-11e6-824a-99973b4b05d5.png)


![image](https://cloud.githubusercontent.com/assets/165937/20084972/a1b912e0-a51a-11e6-990a-e568b0f4ff11.png)
