### ISSUE TITLE
Uploaded and parsed KML data needs to be re-interpreted into a project-specific data

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#198]

**Comment by tigerhawkvok** [comment]
The first polygon is saved in a backwards-compatible manner as of b79f5e035bf565c5485608ceba0a50ac9a908d8e ; the others are saved under the `multibounds` key of the JSON data. This data then needs to be rendered on a project view.

**Comment by mkoo** [comment]
I"m reopening... KML is not working for me...

**Comment by mkoo** [comment]
closing this one but reopening a more comprehensive KML issue...
