### ISSUE TITLE
Mapping sampling prioritization

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#2]
Mike Adams articulated a need we intend to create by making the mapped data the central focus of the Portal-- specifically to be able to map or model sampling effort and aid in prioritization of "where we most need sampling given where we have results, where people already intend to sample, and the risk models."

So potential two issues here: map sampling efforts to reveal gaps and aid in risk modeling and show where current activity is (active field efforts) See Issue #3

**Comment by tigerhawkvok** [comment]
Implicitly a part of #108
