### ISSUE TITLE
Need additional Project role? add Technical Contact

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#206]
Right now, Project Contact name is the one that generates the citation link, which is not always the case when a Technical position adds in data (eg. see USGS projects).

Add in another fields for Technical contact and email but leave null by default as all current projects will not have a user assigned to that. That will clarify future situations like the USGS projects

**Comment by tigerhawkvok** [comment]
Technical contact is already a field -- does this mean that when technical contact != project contact, technical contact should be used in the citation?
