### ISSUE TITLE
Private projects not displaying area of interest in project detail page

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#212]
this is a basic function that needs a fix.
(see example: https://amphibiandisease.org/project.php?id=10d402861fb5b52d4b08b1ed111740ef)

**Comment by tigerhawkvok** [comment]
Only applicable on public viewing of private project. Some of this was the `TEXT` vs `LONGTEXT`/`mod_security` issue, but AOI needs to be computed even when this is resolved.

See https://amphibiandisease.org/project.php?id=4b7af7ca621ff27ec96a9bd367776079

Looks like `getPointsFromBoundingBox` fails for these large multipoly projects.
