### ISSUE TITLE
Create flat table for dashboard work

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#215]
Basic table with info like

| point | genus | species | country | state | year |
|--------|------|---|----------|------|---------|

to query against for dashboard. 

This should be updated on project save? Or on dashboard view?

**Comment by mkoo** [comment]
I would suggest adding in all the required fields and minimally:
basisofRecord
diseaseStrain
lifeStage
Test_Method
infection%

but how about all the fields?

**Comment by tigerhawkvok** [comment]
![image](https://cloud.githubusercontent.com/assets/165937/22683336/54eb5866-eccc-11e6-911f-3dda6f4e2d46.png)

**Comment by tigerhawkvok** [comment]
Fixed at 62569cbf2280adecdf3fd4ec258be97ab2c80d4d
