### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#22]
> **More thoughts on Permissions: really two layers are needed. Permissions for the Project (edit rights, upload rights, private/public) and recordsets the latter (private/public is inherited to the record level). should we allow record level editing?**

Opening an issue for an on-topic discussion of this!

>My initial plan was binary permissions (true/false), but if we want to go more granular, HOW granular? Just another "superuser" role = another column/attr? Or enumerated permissions?
>
>- Read
>- Edit existing data
>- Edit, add, or delete metadata
>- Add data
>- Delete data
>- Change permissions
>- Change users (Add/Remove users onto project)
>- Export data
>
>If enumerated, we should then decide certain role categories with buckets of permissions.

**Comment by mkoo** [comment]
Do we need a table? let's try a table:

action | Project owner | Editor | datauser
---------|--------------------|---------|----------
Mark as Private or Public (Project metadata) | X |  | 
Edit existing project data | X |   |  
Edit, Add, Delete record data| X | X | 
Upload dataset | X | X |  
Delete dataset | X | X |  
Change permissions | X |   |  
Change users (not sure what you mean here) |  |   |  
Export data | X | X | X

And superusers like admin can do all.
