### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#221]
"No results" are the only results from Search in Samples or Project buttons, Taxon filter, etc

**Comment by tigerhawkvok** [comment]
Errrr ....

![image](https://cloud.githubusercontent.com/assets/165937/23525395/357e7560-ff43-11e6-88d9-d8cb560f09a7.png)

![image](https://cloud.githubusercontent.com/assets/165937/23525406/431e8be2-ff43-11e6-8627-e22cc9dfe76b.png)

[Doesn't replicate in Chrome 58 (video)](https://github.com/AmphibiaWeb/amphibian-disease-tracker/blob/f1258e88ac82873fa8c8b868d204fd3523567c08/meta/issues/Issue221-2017-03-02%2012-26-25.mp4?raw=true)

Also works in Vivaldi 1.7

![image](https://cloud.githubusercontent.com/assets/165937/23525849/bdf1f768-ff44-11e6-92ff-0497b1d918ef.png)


MS Edge 38:

![image](https://cloud.githubusercontent.com/assets/165937/23525872/d7bb595a-ff44-11e6-863b-ee09f89ae278.png)

![image](https://cloud.githubusercontent.com/assets/165937/23525900/eff62716-ff44-11e6-9ee5-5c911f66f978.png)


Firefox 51

![image](https://cloud.githubusercontent.com/assets/165937/23525933/08e3d7aa-ff45-11e6-9aae-eb8bbafcc88e.png)

![image](https://cloud.githubusercontent.com/assets/165937/23525939/0faca06c-ff45-11e6-859f-aeb3141d58b9.png)



Maybe was related to [the AWS outage on Tuesday](https://arstechnica.com/information-technology/2017/02/amazon-cloud-sputters-for-hours-and-a-boatload-of-websites-go-offline/)? If it took down Carto, it'd break the search....

**Comment by mkoo** [comment]
FF debug notes:
Turn off geolocation in FF (about:config then geo enabled= false)

Some adblockers may be interfering so disable for the domain (no ads here!)

Still very slow load time, which needs some testing....

**Comment by mkoo** [comment]
Works!
