### ISSUE TITLE
Add a toggle map layer for point data on Project Browser map for Diagnostic Labs

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#223]
Data might be as KML or as Google Maps layer (MyMaps) or as Fusion Table layer

**Comment by mkoo** [comment]
Adding feedback label: on second thought maybe just a simple table that we can update easily is all we need? Allow searches by state so people can find a lab close to them.

**Comment by tigerhawkvok** [comment]
This is a duplicate of #150
