### ISSUE TITLE
Dashboard chart feedback

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#232]
- [x] Rephrase page to "Data Dashboard" instead of Disease Summary Dashboard or Summary Dashboard
- [x] sort histogram from highest to lowest values going from left to right so that 0,0- is the origin for all the datasets (For all generated charts, should be the default)
- [x] can remove the green bar for total samples on the Sample Counts default bar chart
- [x]  can remove Group Values and Show Percent toggles
- [x] NEW ACTION: when clicking on bar in default chart, show a new chart that has just the country's data binned by species and sorted by species, (positive and negative stacked bars)
- [x] NEW suggestion: at top of page allow users to see top 10 by species and Top 10 by countries with two easy buttons

Related to #176 Dashboard to summary stats

**Comment by tigerhawkvok** [comment]
Top 10 preview:

![image](https://cloud.githubusercontent.com/assets/165937/26333256/1f59f5d0-3f11-11e7-9d6c-600cee0c1bdd.png)


Chart ordering:

![image](https://cloud.githubusercontent.com/assets/165937/26333268/2eff4490-3f11-11e7-8872-9c1badf2b2d7.png)


Genus lists:

![image](https://cloud.githubusercontent.com/assets/165937/26333291/56e4c5ca-3f11-11e7-8e9d-07b0ad1a10b1.png)

PNG export of visible chart:

![image](https://cloud.githubusercontent.com/assets/165937/26333327/9bcaffa6-3f11-11e7-818d-85333964133f.png)
