### ISSUE TITLE
Dashboard counts should be restricted to authorized entries

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#249]
No results for *Chalcorana chalconota* even though it appears in Top Ten list with 219 samples!

**Comment by tigerhawkvok** [comment]
Dashboard needs to only show authorized sample counts, like the search -- 

https://github.com/AmphibiaWeb/amphibian-disease-tracker/blob/v0.12.11/admin-api.php#L2172-L2204
