### ISSUE TITLE
Error Dashboard: toggling on Include Unnamed Species.

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#259]
original error:  "error looking up bounding boxes" which I could not replicate. Instead I got a chart that shows 2944 samples where genus is null.

**Comment by tigerhawkvok** [comment]
Verified overall functionality with Rana -- with unnamed species, has 44 counts:

![image](https://user-images.githubusercontent.com/165937/28075910-c2d68e90-6611-11e7-89f7-69c412d39775.png)


without has 21


![image](https://user-images.githubusercontent.com/165937/28075939-d49b5f66-6611-11e7-9f5d-ce6d0bd3fa76.png)
