### ISSUE TITLE
Broken link to update!

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#260]
Please update:
http://www.biscicol.org/templates.jsp
to:
http://www.biscicol.org/template 
otherwise  404 error!

**Comment by tigerhawkvok** [comment]
Ok! Just got back to my computer and I'll update that repo-wide

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tigerhawkvok** [comment]
Also fixed in the documentation

**Comment by jdeck88** [comment]
The redirect now works for redirecting 
http://www.biscicol.org/templates.jsp
to:
http://www.biscicol.org/template
