### ISSUE TITLE
Error on Species profiles in Dashboard

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#281]
REcently something broke and now any species profile (eg. https://amphibiandisease.org/dashboard.php?taxon=Afrixalus+dorsalis) returns this:

![screenshot-amphibiandisease org 2017-10-26 14-29-50-138](https://user-images.githubusercontent.com/2523089/32078096-8ab70bd2-ba5a-11e7-9c88-a982043fcbe7.png)

**Comment by tigerhawkvok** [comment]
I think this was a transient error.

![image](https://user-images.githubusercontent.com/165937/32088067-65d958c0-ba95-11e7-8cfa-a5582622373d.png)
