### ISSUE TITLE
FLAG_MANUAL

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#283]
What is this value in the country field? it shows up in data dashboard stats and should be resolved so it is not mixing up other country-based stats (if at all).

**Comment by mkoo** [comment]
really leaves users confused!

**Comment by mkoo** [comment]
Fixed at the data level today with a manual update by John but would be good to understand how this happens-- we can add a country list to validate

**Comment by jdeck88** [comment]
Michelle updated the country based on coordinate, john updated the database.  Also, changed 'USA' to 'United States'
