### ISSUE TITLE
Sample public, pre-login page

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#29]
Do as `home.html` initially, but at least have something in place to eventually become a new index

**Comment by tigerhawkvok** [comment]
Got some stuff up here:

https://amphibiandisease.org/home.html

**Comment by tigerhawkvok** [comment]
You can see the content and update it here:

https://github.com/AmphibiaWeb/amphibian-disease-tracker/blob/master/home.html#L154-L183

Docs for the `<paper-card>` element: https://elements.polymer-project.org/elements/paper-card

**Comment by mkoo** [comment]
Yay-- good concept!

**Comment by tigerhawkvok** [comment]
Closing this for now, and we can open up specific issues for changes and iterations on that concept landing.
