### ISSUE TITLE
citable accession/ record-level GUID?

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#34]
Use case: accession code or recordlevel GUID or both for citing in publications. May need community feedback about which is priority (one or the other or both). 

Using FIMS will allow us to mint a doi/ark for this purpose but maybe we also need a sequential GUID? Would this require ADP to use the FIMS uploader then?

More discussions with Deck needed.

**Comment by tigerhawkvok** [comment]
Login to FIMS currently throwing 500 error

```json
{"fgc":null,"dp":{"time":"2016-02-21 14:56:17.635","usrMessage":"Server Error","httpStatusCode":500,"developerMessage":""},"server":"annie","execution_time":679.37016487122}
```

Blocked on that for the moment.

Emailed John:

>Thanks John!
>
>I played with POSTing, and I've been consistently getting this response back:
>
>`{"time":"2016-02-20 19:45:02.225","usrMessage":"Server Error","httpStatusCode":500,"developerMessage":""}`
>
>Thoughts? Based on http://biscicol.org/biocode-fims/rest/fims.wadl#idp2031707496 and https://fims.readthedocs.org/en/latest/amphibian_disease_example.html , I'm POSTing "username=amphibiaweb&password=[SENT_PW]" to "http://www.biscicol.org/biocode-fims/rest/authenticationService/login" to get this.

**Comment by tigerhawkvok** [comment]
Fixed at b4262070cbe3d8d28dd70dcf9f7bd1012824acb4

**Comment by tigerhawkvok** [comment]
May need to re-address this pending the solution to https://github.com/biocodellc/biscicol-fims/issues/7 . 

Re-opening issue as a tracker.

**Comment by tigerhawkvok** [comment]
While https://github.com/biocodellc/biscicol-fims/issues/7#issuecomment-189803780 says it should be resolved, for a previously minted ARK,

- https://n2t.net/ark:/21547/ALs2 resolver takes us to the next URL ...
- http://www.biscicol.org/id/ark:/21547/ALs2 - returns JSON
- http://www.biscicol.org/id/metadata/ark:/21547/ALs2 - Server error (via the first's JSON response)
- http://www.biscicol.org/lookup.jsp?id=ark:/21547/ALs2 - Does nothing? (via [this comment](https://github.com/biocodellc/biscicol-fims/issues/7#issuecomment-183182972))

Will need to try with new ARK and otherwise ping John on this.

**Comment by tigerhawkvok** [comment]
Via John Deck:

>OK-- resolution system has been fixed!  Here is a doc that explains how things should work:
>
>http://fims.readthedocs.org/en/latest/identifiers.html#bcid-resolution-system
>
>As an example, we know that the ARK ark:/21547/ALa2  can be resolved at n2t.net (http://nt2.net/ark:/21547/ALa2) which redirects to BiSciCol which decides what to do with it from there.  In this case it forwards automatically to the target you specified.  
>
>Identifier metadata can be found either at the ezid.cdlib or at BiSciCol (note URL syntax:
>
>http://ezid.cdlib.org/id/ark:/21547/ALa2
>http://www.biscicol.org/id/metadata/ark:/21547/ALa2
>
>Why two resolvers?  There are two resolvers since the BCID system has features above and beyond what CDL is doing and i'd like to keep them open. I'm going to assume, though, that N2T/CDL will outlive BCID and if/when that happens we can update all targets in the N2T database using information from BCID.
>
>OK--- last bit:
>
>There is a service for updating bcids (see http://biscicol.org/biocode-fims/rest/fims.wadl) at /biocode-fims/rest/bcids/update POST.  We used to have an interface for this but nobody used it so we removed it.  Go figure as soon as we remove it, someone asks for it.  At any rate, maybe its easier to just leave it as a service for you?   Or, let me know and i can bring the interface back. at any rate, the update service should update both biscicol and EZID (let me know if this works... the ID update service has been out of commission since the refactor but good to know it should do what its supposed to).
>
>Username/email can be changed for ALL future ID creations, simply involves logging into the biscicol.org interface, clicking your name in the upper right and editing the details there.  For identifiers you've already created would involve (right now) changing this at EZID which i can do for if you want.
