### ISSUE TITLE
Password reset not functional?

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#35]
Not sure if this is known but not working! (either with link or manual input of codes, neither works)

**Comment by tigerhawkvok** [comment]
Might be fixed upstream, integrated the possible fix over at https://github.com/tigerhawkvok/php-userhandler/commits/amphibian-disease-portal and merged it in over at 6a0f2485ccd5456475343631a120c9ddef0f3758 , will test it today.
