### ISSUE TITLE
superuser admin page

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#47]
View which projects have:
 - [x] datasets attached
 - [x] users affiliated with project        

in edit mode:
 - [x] indicate which fields are editable in project

Also view:
- [x] general users admin and their projects or datasets
- [x] allow changing users permission 
- [x] Total user list

**Comment by tigerhawkvok** [comment]
Currently shows list of users, checkmark if at least one email is verified (!= user verified), if user is admin, options to initiate password reset, view projects, delete user

![image](https://cloud.githubusercontent.com/assets/165937/14941291/d96e86fe-0f4a-11e6-8fee-cbd4bb4f3ad7.png)

Project view shows projects, author/collaborator status, and if dataset is present

![image](https://cloud.githubusercontent.com/assets/165937/14941295/f82ea51a-0f4a-11e6-96b8-7b13ec0d1023.png)
