### ISSUE TITLE
dashboard for community sampling activity

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#49]
page to show visually (a map) all the project transects as well as being able to search for projects by species, by pathogen, state, and users. 

This touches on #3

**Comment by mkoo** [comment]
Let's agree to build this concept into the current project.php 

When logged in, use the icons:language (globe) to indicate links to project,php (i.e., replace the toc icon in upper right)

**Comment by tigerhawkvok** [comment]
Fixed at 953e2221cb99dd070be005c136b7337515dfcd6f

![screenshot 2016-03-03 21 18 51](https://cloud.githubusercontent.com/assets/165937/13518725/bd461016-e185-11e5-8d7d-1dcf218d6498.png)

![screenshot 2016-03-03 21 18 37](https://cloud.githubusercontent.com/assets/165937/13518726/c3b0d15c-e185-11e5-91ee-65197b760e15.png)


![2016-03-04 05 18 38](https://cloud.githubusercontent.com/assets/165937/13518757/15b52ac0-e186-11e5-95c9-60b7f38b5032.png)

When tapping on a bounding box, it'll take you to the project page. The bounding boxes are all unauthenticated bounding boxes, with the decision on precision only done on the individual page for speed.
