### ISSUE TITLE
Required Project fields

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#52]
Indicate on interface that these are required: (asterisk or underline color default not tab-dependent)
 - Project Title
 - Primary Pathogen Studied
 - Project PI
 - Project Contact (defaults to register user)
 - contact email
 - Diagnostic Lab
 - Affiliation of Project PI
Project Area of Interest

**Comment by tigerhawkvok** [comment]
Fixed at 40112abbd5bc1e8bbc1461eede84f2b7ef6ddc6b
