### ISSUE TITLE
View of Datasets in a Project 

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#56]
would include ark

**Comment by tigerhawkvok** [comment]
Download button to raw data file added at d5bc6a5cc8dc51ade85425276cc031c3680bfb39

**Comment by tigerhawkvok** [comment]
For multiple datasets ( #55 ) , set up a fragment-based url that highlights and scrolls into view the matching dataset, eg., https://amphibiandisease.org/project.php?id=e3b7bf3e7bad2cdc676fcf3eed77eff9#dataset:b7d5142e8876c5b5714b45f716df1fc7 

leads to

![image](https://cloud.githubusercontent.com/assets/165937/13545361/a25e3428-e23d-11e5-9a10-13bb09cdf587.png)

Actually having the ark resolver point to those fragmented URLs is blocked on #55

**Comment by tigerhawkvok** [comment]
Functional sample data ARK: http://n2t.net/ark:/21547/AMg2

No exposed UI for it yet, but they're being minted.

**Comment by mkoo** [comment]
Yay!
Can DB start using it then?

**Comment by tigerhawkvok** [comment]
Yep -- I've not figured out the best way to expose / facilitate copying of dataset arks yet, but they're all generated and tagged. The other block on his upload is #32 , which is blocked on #61 , but as long as his data is well-formed the validation isn't important.

His other blocks #60 , #59 have been cleared, and [associating the data ark with expedition ark](https://fims.readthedocs.org/en/latest/amphibian_disease_example.html#mint-bcid) can be done after the fact ( #62 )

**Comment by tigerhawkvok** [comment]
Actually, @mkoo , let's hold off on that until I have a moment to change the carto credentials used to store the raw data.

**Comment by tigerhawkvok** [comment]
Moved credential, and got uploads in place, and datasets are being minted ... closing
