### ISSUE TITLE
FF bug: cannot view main map in Project Browser page

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#67]
Noticed it yesterday but blamed it on wonky airbears; pretty consistent now-- no map but it's footprint is there! Only in Firefox (Mac)
![screenshot-amphibiandisease org 2016-03-15 09-31-14](https://cloud.githubusercontent.com/assets/2523089/13785471/ea997396-ea90-11e5-88a2-a25ced0c502f.png)

**Comment by tigerhawkvok** [comment]
Doesn't repro in FF45/win10

![screenshot 2016-03-15 09 34 51](https://cloud.githubusercontent.com/assets/165937/13786278/1f339548-ea94-11e5-9192-44f9d2389e00.png)

**Comment by tigerhawkvok** [comment]
@mkoo can you also give FF/OSX version for me to test against?

**Comment by mkoo** [comment]
i"m updating... maybe the kickinthepants to jump start map viewing

**Comment by tigerhawkvok** [comment]
Can't replicate on OSX either for FF45

![screenshot 2016-03-15 21 44 06](https://cloud.githubusercontent.com/assets/165937/13802270/5b559cde-eaf7-11e5-91a3-951a168be85e.png)

**Comment by mkoo** [comment]
Figured it out: AdBlock Plus is blocking....
added exception and works now.
