### ISSUE TITLE
Restriction on project creation

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#81]
Via @mkoo :

>any thoughts on authenticating who can create and upload data beyond what is in place there for bots? I think we should continue to allow anyone (who's a person) create a user account but perhaps have superuser control or other mechanism for which users can create projects. I assume the validation steps would take care of any malicious uploads?? but let me know

Potential solutions:

1. Restrict creation to verified **.edu** email addresses: Add email verification to userhandler, add columns `alternate_email`, `email_verified`, `restricted_email_domain_verified`; variable `$allowedEmailDomains` and `$allowedEmailTLD` in configuration
2. Restrict creation to users with verified phones. Already in place, but needs [Twilio](https://www.twilio.com)account with funds ([>$0.01/text](https://www.twilio.com/sms/pricing)).
3. Require (1) and (2)

**Comment by mkoo** [comment]
hmm, (1) is interesting alternative; can we add other domains like .gov or other? Most of the other users will be in a government agency here and abroad; Not a fan of (2) or (3) since I think it would eliminate me! I was thinking of more manual verification by a class of admin types but this might work better.

**Comment by tigerhawkvok** [comment]
Yeah, I was thinking that `restricted_email_domain_verified` would be true if:

1. Email was verified (and alternate, if applicable)
2. Either matched an entry in the array `$allowedEmailDomains` (if an array)
3. At least one that matched (2) matched an entry in the array
`$allowedEmailTLD` (if an array).

**Comment by tigerhawkvok** [comment]
UI when restricted:

![image](https://cloud.githubusercontent.com/assets/165937/14377192/59205bf0-fd23-11e5-8318-556943dba9d0.png)

Verified emails and setting alternates

![image](https://cloud.githubusercontent.com/assets/165937/14377302/b7ef23d2-fd23-11e5-95b0-1b13d0756e58.png)

Verification UX:

![image](https://cloud.githubusercontent.com/assets/165937/14377468/93c622b6-fd24-11e5-8918-d77171b62baf.png)

Context-specific hints on unrestrict dialog:

![image](https://cloud.githubusercontent.com/assets/165937/14377484/b20a9306-fd24-11e5-9f31-017257458e4a.png)

Unrestricted accounts:

![image](https://cloud.githubusercontent.com/assets/165937/14377496/cbdff820-fd24-11e5-8eac-1856b3a348c9.png)

Restricted landing:

![image](https://cloud.githubusercontent.com/assets/165937/14377517/d7709e88-fd24-11e5-976c-cf17afa4976e.png)

Unrestricted landing is normal, but with a green verified badge:

![image](https://cloud.githubusercontent.com/assets/165937/14377525/e56c6a62-fd24-11e5-9fce-2bf60e96bef4.png)

**Comment by tigerhawkvok** [comment]
Closed at 48e7e769dbb07f5c2b64d8ce16f7110dd8847808 with fix of #86
