### ISSUE TITLE
Upload data button missing on Edit Project page

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#90]
Needs to be easy to find and allow all the same stuff as Create Project options with the options to replace or append data. (exists now on right)

**Comment by tigerhawkvok** [comment]
Hm, it's there, but clearly needs to be labelled better

![image](https://cloud.githubusercontent.com/assets/165937/14577076/2b1d58d2-0324-11e6-9f7a-3b689807ca95.png)

**Comment by mkoo** [comment]
Not on mine! From  Edit Porject
[image: Inline image 1]

**Comment by tigerhawkvok** [comment]
Weird -- apparently inserted image doesn't show when you reply by email (eg, can't see it).

**Comment by tigerhawkvok** [comment]
Fixed at e55f38130e98e9d4b6d1b0614c9aa898536e9fba
