### ISSUE TITLE
Cannot add users to a project

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#91]
I know you probably havent worked on this yet so FYI, this is what happens when I try to add a user (you) to my project or change ownership: funkiness
![screenshot-amphibiandisease org 2016-04-18 09-41-39](https://cloud.githubusercontent.com/assets/2523089/14612033/f9898e44-0549-11e6-89e2-a0168c63494d.png)

**Comment by tigerhawkvok** [comment]
The user gets added, but the UI is borked.
