### ISSUE TITLE
Debug bugginess with FF(Mac)

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#99]
Just FYI, when logged in as user, right-click function on Bug Report to enable debugging does not work on FF/Mac.  Works when user logs out. 

Works on Chrome/PC and Mac. I'll have to test on FF/PC's later.

**Comment by tigerhawkvok** [comment]
Doesn't replicate on Firefox 41, 43, or 46 on Windows

![image](https://cloud.githubusercontent.com/assets/165937/14941000/f4ceba8a-0f41-11e6-8dc1-1289ff357287.png)

![image](https://cloud.githubusercontent.com/assets/165937/14941009/2ee85442-0f42-11e6-8eb2-8675907cf949.png)

![image](https://cloud.githubusercontent.com/assets/165937/14941025/a1e6f714-0f42-11e6-93e3-4b4b49a4fe83.png)

**Comment by tigerhawkvok** [comment]
Intermittently functions on OSX. Seems on OSX, event binding needs to be run later or delayed (perhaps batched after `Polymer.ready()`
